OPENQASM 2.0;
include "qelib1.inc";
qreg node[3];
creg meas[3];
h node[2];
ccx node[2],node[1],node[0];
cx node[2],node[1];
x node[2];
x node[1];
ccx node[2],node[1],node[0];
cx node[2],node[1];
x node[1];
x node[2];
h node[2];
ccx node[2],node[1],node[0];
cx node[2],node[1];
x node[2];
x node[1];
ccx node[2],node[1],node[0];
cx node[2],node[1];
x node[1];
x node[2];
barrier node[0],node[1],node[2];
measure node[0] -> meas[0];
measure node[1] -> meas[1];
measure node[2] -> meas[2];